RMTEAM-273: Update formatter to support all rhino mocks to moq conversions
rubicon-oss/RhinoMocksToMoqRewriter pull request #38
Opened 2021-05-10 07:17 UTC by derlistigelurch

2021-05-11 10:28 UTC, iam-mholle requested changes

2021-05-11 10:28 UTC, iam-mholle commented on Application/CompilationLoader.cs
> +      Workspace = new AdhocWorkspace();
Why is the instantiation needed here?

2021-05-11 10:28 UTC, iam-mholle commented on Core/RewriterOrchestrator.cs
> +            syntaxTrees.Add (Rewriters.Formatter.Format (currentTree, workspace));
![surprised](https://media.giphy.com/media/l3q2SaisWTeZnV9wk/giphy.gif)

Wouldn't this format the whole file and not just the rewritten syntax elements?

2021-05-11 10:46 UTC, derlistigelurch commented on Core/RewriterOrchestrator.cs
> +            syntaxTrees.Add (Rewriters.Formatter.Format (currentTree, workspace));
no it just formats the annotated nodes

2021-05-11 10:56 UTC, iam-mholle commented on Core/RewriterOrchestrator.cs
> +            syntaxTrees.Add (Rewriters.Formatter.Format (currentTree, workspace));
Ah I see, confused the 2 Format methods of the class.

2021-05-11 11:48 UTC, derlistigelurch commented on Application/CompilationLoader.cs
> +      Workspace = new AdhocWorkspace();
hmmm... it's not needed at all, it can also be null, because the workspace will be initialized when loading a solution or a project.

2021-05-11 11:49 UTC, iam-mholle commented on Application/CompilationLoader.cs
> +      Workspace = new AdhocWorkspace();
It should be removed then

2021-05-12 08:40 UTC, iam-mholle approved these changes

2021-05-12 08:58 UTC, merged